/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUHAMMAD SYAFIQ
 */
public class MovieGUI extends javax.swing.JFrame {

    /**
     * Creates new form MovieGUI
     */
    public MovieGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Action = new javax.swing.JButton();
        Comedy = new javax.swing.JButton();
        ScienceFiction = new javax.swing.JButton();
        Thriller = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoMovie = new javax.swing.JTextArea();
        MovieDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MOVIE GENRE ");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Please choose one of the movie genre :");

        Action.setText("Action");
        Action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionActionPerformed(evt);
            }
        });

        Comedy.setText("Comedy");
        Comedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComedyActionPerformed(evt);
            }
        });

        ScienceFiction.setText("Science Fiction");
        ScienceFiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScienceFictionActionPerformed(evt);
            }
        });

        Thriller.setText("Thriller");
        Thriller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThrillerActionPerformed(evt);
            }
        });

        InfoMovie.setColumns(20);
        InfoMovie.setRows(5);
        jScrollPane1.setViewportView(InfoMovie);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Action, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Comedy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScienceFiction, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(Thriller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(MovieDisplay))
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Action)
                    .addComponent(MovieDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Comedy)
                        .addGap(18, 18, 18)
                        .addComponent(ScienceFiction)
                        .addGap(18, 18, 18)
                        .addComponent(Thriller))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionActionPerformed
      String test;
      
      test=("You chosed : Action ");
      
      MovieDisplay.setText(test);
      
      InfoMovie.setText("About this genre : Is a film genre in which the protagonist or protagonists are thrust into a series of events that typically"
              + "\ninclude violence, extended fighting, physical feats, rescues and frantic chases.\n"
              + "\nExample of the movies :\n1.Maze Runner"
              + "\n2. Bad Boys\n"
              + "\nThe Actor & Actress :\n1.Dylan O'Brien"
              + "\n2.Kaya Scodelario"
              + "\n3. Will Smith");         
    }//GEN-LAST:event_ActionActionPerformed

    private void ComedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComedyActionPerformed
      String test;
      
      test=("You chosed : Comedy ");
      
      MovieDisplay.setText(test);
      
      InfoMovie.setText("About this genre : A comedy film is a category of film in which the main emphasis is on humor. These films are designed to make the audience laugh through "
              + "\namusement and most often work by exaggerating characteristics for humorous effect. Films in this style traditionally have a happy ending (black comedy being an exception). One of the oldest genres in film—and derived "
              + "\nfrom the classical comedy in theatre-some of the earliest silent films were comedies, as slapstick comedy often relies on visual depictions, without requiring sound. "
              + "\nWhen sound films became more prevalent during the 1920s, comedy films took another swing, as laughter could result from burlesque situations but also dialogue.\n"
              + "\nExample of the movies :\n1.Grown Ups"
              + "\n2. Jumanji : Welcome to the jungle\n"
              + "\nThe Actor & Actress :\n1. Adam Sandler"
              + "\n2. Kevin James"
              + "\n3. Will Smith"
              + "\n4. Dwayne Johnson");   
    }//GEN-LAST:event_ComedyActionPerformed

    private void ScienceFictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScienceFictionActionPerformed
      String test;
      
      test=("You chosed : Science Fiction ");
      
      MovieDisplay.setText(test);
      
      InfoMovie.setText("Science fiction (or sci-fi) is a film genre that uses speculative, fictional science-based depictions of phenomena that are not fully accepted"
              + "\nby mainstream science, such as extraterrestrial lifeforms, alien worlds, extrasensory perception and time travel, along with futuristic elements"
              + "\nsuch as spacecraft, robots, cyborgs, interstellar travel or other technologies. Science fiction films have often been used to focus on political "
              + "\nor social issues, and to explore philosophical issues like the human condition.\n"
              + "\nExample of the movies :\n1. Interstellar"
              + "\n2. Gravity"
              + "\n3. Geostorm\n"
              + "\nThe Actor & Actress :\n1. David Tennant"
              + "\n2. Linda Hamilton"
              + "\n3. Milla Jovovich"
              + "\n4. Will Smith"); 
    }//GEN-LAST:event_ScienceFictionActionPerformed

    private void ThrillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThrillerActionPerformed
        String test;
      
      test=("You chosed : Thriller ");
      
      MovieDisplay.setText(test);
      
      InfoMovie.setText("Thriller film, also known as suspense film or suspense thriller, is a broad film genre that evokes excitement and suspense in the audience."
                + "\nThe suspense element found in most films' plots is particularly exploited by the filmmaker in this genre. Tension is created by"
                + "\ndelaying what the audience sees as inevitable, and is built through situations that are menacing or where escape seems impossible.\n"
                + "\nExample of the movies :\n1. Parasite"
                + "\n2. Insidious: The Last Key"
                + "\n3. Ready Or Not\n"
                + "\nThe Actor & Actress :\n1. Gene Hackman"
                + "\n2. David Fincher"
                ); 
    }//GEN-LAST:event_ThrillerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action;
    private javax.swing.JButton Comedy;
    private javax.swing.JTextArea InfoMovie;
    private javax.swing.JTextField MovieDisplay;
    private javax.swing.JButton ScienceFiction;
    private javax.swing.JButton Thriller;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
